apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rollouts-ingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /$2
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.middlewares: argo-rollouts-prefix@kubernetescrd
spec:
  rules:
    - host: kubernetes.docker.internal
      http:
        paths:
          - backend:
              service:
                name: argo-rollouts-dashboard
                port:
                  name: http
            path: /rollouts
            pathType: ImplementationSpecific
