apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-creds
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgAJJQVcsiu2zcN3+tfOVspu/VtavsRV6p7Uz4vnyNKigIXpMukN4rr5F44uttFZtMEtbeJVbE1/s04ItE2QFO0+Vjo6KPqGPKunPtqIM1uhYnNu3Gb0U4viXl75iOHW0gY7ahngKy7YuQUXZ2aE68Xxnx0T4vk/nqRwu/P3ezThH0jSWC+VmdMkWO4IxxzpUArYnrujGTadUWPbG5xDJ012XiSq+c2np81IEl2+pDTj1LGuH6fxyWhnQzKa8xDIrSYBeuPjd4VvWMzAg4WCZDeiyYmhwxyZo5wZ0vQhbciCORyXUcQkC+8Ielr4zOwUWkV5FCOPh9BbEfFfs7Ol95elRDvgbeHEsSIbk6fDyk/DrBMo7gyjf9ExHopBS3BHW6cFDtERxrKMXk2np1kbTVPZnf47cEyyBDTaGIvzlKq6Tr0Hgs5a+C1qP11cPCPMe9jOHnxcJQueQ/iQgX1Bk6ryp333lUZ4KtxEa9VXtCqTfz9Vyhc/+RTa6Xh29k2Ue1/YaLezaxI6pRXaR1wRmlmP88gk+/3O8vJ6vp8hneJsgOYhZyHbu+ZUdBKr8AP5YRQST1fNV06TjtkBQCfZR+XJUg1XH0zGTMvn9FEkEG/9xVaBWFffEzugeSr+hmEXSXsl+Tw4RVaat/6EL/Bjie+H/jgIoZZ4N+ajLoGEjWSnyfX60T+0QTa/IX+t+nyGxMSVyPesy5xLePrIZJshGj8Sj0fUnte0VzTrw7UkBEu3MyM+WqzoiX0h0bAZhKsWkKneFjGveAn/9GEbvERtojK9BFCdJNmj1+ZKyJ8B+2ommgp26zkqb9RdpA==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: aws-creds
      namespace: crossplane-system

