apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-credentials
  namespace: crossplane-system
spec:
  encryptedData:
    aws-credentials: AgCMd5ijwgsCaupSzJh10YMsGGO29lmEYmewMA0hlXdzBwUbHAzIsWubDbl9KBMp8/vesc3SeZGKU0CFTWGV2kDBWvKvvqzLY7WFkEDsFqx5jlyznMfQ5A2r3yWmMgICo+D4eA3zhh9+cqNmpyVjcPK8qqMN91BVFGbf1fAR+CrBTPjhueVMtY2QDiBwz5QKy109RuROsQtTPtIacgb9aShq3xNebWBWTB7GW1iqokXvTgH5frcBnrL0AAM1stDzjyGHDV9B7J++VV2Xq+UJGMAUW+OuOv2BfydAV//bQz0pf8zYC4TWwCo0Tsd+nIQ98cHOaZN7217zkuURJaGuy2mSLpR/dLKioRc8mVGSd3muGl3KoGSMigeDdglv+qty9MbcF6DTumiYERF3WLP42J2P9dB5kALwQErDZSVUVr9GQmJjHn0t2bbnzI9/NesIgp8yQbI+4mEIx8BguRMeogCWt2Ztmt5iBQLVTM5q/ABdsOMqu0D1WiMuqau6yRs6Zwt8HZ6gWFSQ5RdLm5yPiejOO+kr4Iv/oH4AnfKo1YF/AUXrifRfwKj3RnR8egK2xubSs6qIAsVfcWuuo1lcb4wriUXrqj3cAD56pLCT3zCh9nFkdIsp2bOKTAH6GI8dJ9YJxbI/XvElImHRJfY1kKceiSF7p3UtRDUbKk5wMV2opoaxr6mZW0/b1qnV0H8Ko5X+mmeXOo82+1/NaIyW40XDIDazgqiTpFqwYX8y/NqmKH5qJin65SY5KYaUQeG0RTW27eAF2MBsLjglKOVnlHrcJHMbnqtEHGERkm1JH1q6FBwMbTHCtrGfyQ==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: aws-credentials
      namespace: crossplane-system

