apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-credentials
  namespace: crossplane-system
spec:
  encryptedData:
    aws-credentials: AgCFUTBS7z+01TY5/mfDmxpnFHTIKBhpE0hEhdqUldX98Iyxd1MsBPrlRwFd5Ks2ZWuNjEIfRf/+OwVvBsTM0K0hu72Twfmt+JIy/VhoIhIKkXkxbRM5t5jjlcNvO7ZwGP9r/ZrnCBdELKUEX6uK+ljVN2dlZkpcPCgTbSfygiKx7z7060K/mAToGd3dIFA3r6ITFvpMuIE42Q+lOk1423YElz8TSFBzxUpqXDpSzV4FGWe7egK+JvlVN9p9/G1FjRwUZtr8WzPyWvZH7xyGoT6IHW12l3zLZNAkTJdo9/Eafsp3dwDYHWNkcuU0758Y3kAjrXoOGc/SvXLw8GJZXPVheakXSQCyTjDISP7V1C/OgsxDxNwWmsZn5vnwP2bP5Bl6tR1iw+pDAAMxz9+iBykSXN9M8+kuBGxCINiesUefPRKzTYcsd41IosUJ/WqrZ4FWacVK3sJByeDVydkZ7YWhNyem4itYx1nIvSEZ+wJ5fbVDj8k1P9+bbavbA3byBfcvXe7CUPxDCBpkCaO404AVKWGXz+1Z1IigBEFwwLzHK2ogIvGY9QqwxFHEpIhCxzK/zTfxFCgyXBzh+P33N3TZPOyDIMPoff2CVt8wSc36ckXkotVdNuJ5IT7KBdqCP0wdicAGYMYD2NTFW4ZW+5yMxETSo7nXS8dk+CKR2hEaV/n7cw1VAAzB6fnI8xYqKq88ljOSCH4GRHmYTWyh3+blOBUoW1VfYfE6bUqqPytAs09aF3Vlviks3QrPx1jsKTZWjPgpM8XDfb59Ii2DCXBHK3hXBG4AApX/RRqT59qKkPhDpPPguUX8Jw==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: aws-credentials
      namespace: crossplane-system

