apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-credentials
  namespace: crossplane-system
spec:
  encryptedData:
    aws-credentials: AgBmAjBNuhZY0QIPUYskVcETeZbnlHMl8UNJ8rH6UJ0GGJwIJPvZ1kJ3mau9PThLNXEzceMxdIYLz4JhHB5zY8zd046AoI9PxwYt0O7dl59tu2WcV+rIotb/MxDIaf6XaULLrUVzLP/GU4sTDjH1nwzUAZtyeV/b4caJjPBBwNzGDe6F0bd89S/65vuMWnycMc6jlR7Bnm+pLm3eNfdc7Niqz5nBra0aLPCJ9PRQ2iiUD3F8SupA1IX4DXoDwPa56OtTzjUfv9oeyB+A0DrbFV8mkqrmwrAqQNti1s2mhLsYp+o2wWIhNhM0NPTl2lmsDjQqFSrktQOBGKfA94CxC/8o9FXB/VuPfiYyXDHpgi/GDXeRdJfsTowgT3N6jTVgfOPO/QMFb/npWet8iGSbaJOfizPdgQnqHIfae587P1Kfnc0ICgkYSzntI2Sn/YHgIuoYAAzJJzxWxm5T23Wg13eJGaZS/QGbyUWKtKG7AGZqYHORXzZpvX1R1pH19kLkROSKZkoicCzVAtAiWSYndfMcd32lvoDPvSO3RkPxxtgKpyys7A5CK56oXkiAZI0JYC5AKFZDSga/uaiJGjiDanf1w83llQCdJaOOuB1WtCKNYvmBUUXOkiD9p6BNiI5PQwiIjbQLFLrH89EYeSbyoO8MhyEhw/ftI1f2/817PB5/NW6z4FSFyNWF4boamGmroBq+Zns+aOGKiIfh6f8ctWfOsx6EYnxUn2kq5pHfYmSFNhL7O0d6flX6vkLw2dcWHk/2TFu5ONNr3pbMEaF9O4pGqulq022TEOCk2FiOxHn8eEamIDroX865BA==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: aws-credentials
      namespace: crossplane-system

