apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-credentials
  namespace: crossplane-system
spec:
  encryptedData:
    aws-credentials: AgBbIRHHPJyN4BfL19KDxugyOSCVof3cp+HDoscR3Qc0lnMptR/gdGk43/3OS4MbyhBSsU/fRAmlBFFDldT2pOnoW7ysW0f7U8wSMP+HMkrKju/xtRA1Yf6dkX+wLWEAEHw+4JXIV9CsgtqdYuaPEgMda8tTT0hBtsHSiuLQsodMr4eQEpm0o8rMUM31yn2kFTCZLbkDzbiJVFzlq7MbLa8VQUXHSmbqLgVONzfjyH3seRxLqS+C4+cZd2+m0q/rybZ2RvUrWWIq18pIBHjdxvfwQsHUm6dvdnWbqud+NHEZw7He8BneAjhXtZLaCBD/GdI4CuWmJthLW2EzTsaTGjby+y2T7HHBCLuIqqptEQ1iD0gfNvZNdHLQjlAgmslkyq1t1cPAcuKnp4OheckwPb+ShI6IEoL9yAH3vxnanrorf2LIlhBd5UB+GCclzfHJHgJ5Id25izbXYzu4XvIrWC2nNBmac8cTVNAYDQB0OZPqGecNxOJt1mGOIsPuH1APAZ7hE59Hea1RNZ/tewlSS/aoVV7KkSSF1gfupBi+ijU99McZmwS6fpMcITSekIMuh8CfSuaS708cl9R/6vyIXZeFeVAFb+85o7AYpv5K+3+rbU9km4bHi19bXvC3gx9VfunxecJxL40BzwcE2W33zrO2B9qbZX8v3nPn72d74gqfb49ZFohhtp/9omtI0KTAgHJLfGn7pUDgvGe4LQkZdk4PO7G1ciwuoMUWHrPwomV+8D8cEXeMfpEptjQLd/s2GAf3tId/YbonQruYF32F/crTnlq4o/C6qvTVIJlW8SaOZU1frR0+yoavIQ==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: aws-credentials
      namespace: crossplane-system

