apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-credentials
  namespace: crossplane-system
spec:
  encryptedData:
    aws-credentials: AgA4yCf+Wo/daC17JvfGjSBUovn7+tq5o2tCrT7Rp965DnsXlasfI0RltM0ESbHRU/C2NSj9KpJP4oMIb72ggSWA5sXBUGwcpxM/3xF5tWpZxz3MgTKwppa6AVJLq3K9xpOfY1mbGgBbVhHY3aBjGftqw5SOhm+o2mgaKrLdh3LB1cjGV10cdye/sRH/qq7V0AV0TwPZogyhDNIXgEY+UzSRwgQfK+y9Xww5MGtoW1RhCtux+hcgIqjObteoRQWNhIS5ypV8ZQOdENvlduh4Uy/GtPZtHq76sAC7JqnvQvzsmhOxzs5oF/wD4DQkZ7UDIW2zGCR4ks9XyQN5eyGs/wlTYqgxEHI8SHxkyrlMGfQ80xxZ5SyqGM7dyaTnRLzb4gsznrgBPRYgDZNfC5ktYdoq8a2iFiNmGnLna57uZt8RllTTlGusH5oEjq5Vusq+Oeq3VL7ACgIJ3Q/HAm0AmT6OTJDMhpl39ZT4Cd/gbllr/BW0XgS/hV0ZlIgqNis7xSnjzk5mT0Zwg0mKrRoky/W5Fgj2YAGA6kd7lbpaEyr02M+7pnHByGVzaSAms88aPhkk2DTIhLppf9Jo4MxVfjGWjCLZ/+KTToUXTJvnT5/lZ/+F52dpSu9mc0PE8poz08NLjhkyJw8xLhYeWFAbaKLg9RlXTHXD6RQ+CeP21QjjhROJpkbkzEageKstW8DshYwVZw4sO7T2c7hJynWhyXaOz2KIeYKd0EEUtWmElhi2aedcMssFBCw6VepvinpnxW3O2mDP8PyzKLMntARFSlpkiN9BTOg70ecnXkxLAEtj4Q8W42AL9GKang==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: aws-credentials
      namespace: crossplane-system

