apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-credentials
  namespace: crossplane-system
spec:
  encryptedData:
    aws-credentials: AgCk+kCCP7M587dvaup5xjqaSOlHEgksKpF2V73cfg84J+ebSf5/jb5HlbTxyzJq7Psipk0LU7UUdS8FtiMobmqv95rQtFcXDnDPrEdfkRt8IQM2DjpnVRy98iR3Dx31bjuJzGS/nvKGwgNqnIGmvhaHRqtslWZ+xyQZ5cS01JOYkJOaiSZ3q1K0hWAmoNh8+3W9dECwTErgmMzsL5IlcG5WZJhVuUCaIHCxQq4MalHOUxUjxMF5NZ1/SmWQXluApTL0IDO/kydSCJvNATdNwHe//YGkh26RMVMv3aFMnm1ggOwOJQPJozUzGp7ibPMU+JZdXVFqGrq9wW0djZcx4IFOwCgn+yn+Wb5mO219y8WIsMRahLoZ3dhQYOuB6/bYfkqYZvty7xhMpg4mXMkk5D+VJMuQpPZJNS+i+zmb/Phhpi4Q2svBnRMnGS4YZMubyCsqffUXYm0zLAMPN907IdQ1q1vJ85aNlIFzNaH6DSnrepfXMZoQzeJzJpVtC4eUWYrksvDPTtNVViqPqWZ09VLFuyhXPQm0O5BK/YSMAqgGek9YDQ8Q9jonl8MjulIvAVnTKXABY0HRFH9ugLSvy/QPLFxTwlNJSkhJ+GXKOsjnX50XNRtzRC5zvibdlqEXiVsCZkIekgk88qBv7hOXzqUqnZ1p4DOP45S7Myw+JKizQHxBjak3BDflu6wgVp84aUAQJTAkJYJxtszn6rMxuNYPDi9KApY8Heo//oqDuDEW77GHgcwOCdiDKxKy8DdQBQLlDonxh3mK2M4Ve+IEek6OVQmEj87v5EzlfXC7Q70VpT2s08Ca6s4Saw==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: aws-credentials
      namespace: crossplane-system

