apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-credentials
  namespace: crossplane-system
spec:
  encryptedData:
    aws-credentials: AgBm3uXjQjQEGZN95MlZoTjBXJeSADc1YRp5mOxFK6l7Z4jWNy63TMLpH8rJacYGJGdkoWmZAEG/ywFT8AHPp/TK2Zj59FWQR5KBqYZ2G86+1eNIbA56Quxt7V40Yfaodww50p3TqP4F/hpOHCBFTYuqdMoy+wCAslyG6Z0oV5XTD5a4MOPxt8P8JeUg4crKy6lzd0rNjS0ttyzIMDKSGm72CJo8xugvsgMCmDWUUZvN1uikO7o14byWifEpA5pXRmwBx7zQhNalgMSMTulfQ+KGjI920ZXNY+vCS8wdEV7+R0lctbjbmN25kD+QqGC5pQgtHvd+qL/Er1utv0gmlCq6+jQ/7mlmNMBjfUjC1H9cfBgMO1CzXqFkdG6LDva/tVHeq2A+rbrqPruGwrgGmpyPqDN2tKIoDiN6gZL40Q3C5kyruiLTWb00fBpIxGKwVtATqp7GYA2GbfOL0CUEAFviKnTrnUEl4Usdk2tk0fAUwBLe9qnShkvbUYTVQwGaPg3xvDpcx5eR6HLr/PKyuY0hXtQC2qaWpfTbozJdoCOdkiM1o6zAXt1WOA8zcrlPmmF2+UjlRzyN3qw1dp6Vz9CzYKpXE4daihimJDPwj78nC2Cvm18zztUdVKYNKHP8s1iHr/MQfVXl8njab5HigpHZ1t+C35+/oNF4mBSxogj6F7qN8J2TKO61L4anRmakTxOqYosy5KSVZhPPD1EVCFi1SpUDbS+xegtDRZSeOCFsjkZQ9dMDyTpuRAuukmu4RTVZEiwBn+PssV+SRWXbHg4Mal21BiyACTfGFJyreiYglANmxFl5kKNSog==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: aws-credentials
      namespace: crossplane-system

