apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

helmGlobals:
  chartHome: synced/

helmCharts:
- name: helm-chart            # this is the directory within /synced...
  namespace: argocd
  releaseName: argo-cd        # this is what you want to name your deployment
  valuesFile: values.yaml
  includeCRDs: true

# !!! NOTE: Always use separate fucking generators for configMaps + HELM
# !!!       REMEMBER THIS FACT!

generators:
  - generators/configmap-argocd-cm.yaml

resources:
  - synced/vendor-manifests/cluster-rbac
  - patches/traefik-middleware.yaml
  - patches/config-map-tls.yaml
  - patches/cm-cmp-plugin.yaml
  # - synced/argocd-extensions/manifests

# patches:
#   # reset the crbs to `subject.namespace: default`, so that argo-cd will later change them to the actual ns
#   - target:
#       group: rbac.authorization.k8s.io
#       version: v1
#       kind: ClusterRoleBinding
#     patch: |-
#       - op: replace
#         path: /subjects/0/namespace
#         value: default
