apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# resources:
# base Argo CD components
# - https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/ha/install.yaml

components:
# extensions controller component
- https://github.com/argoproj-labs/argocd-extensions/manifests
