apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# namespace: argocd

helmGlobals:
  chartHome: synced/

helmCharts:
- name: helm-chart
  releaseName: argo-cd
  includeCRDs: true
  valuesFile: values.yaml
  namespace: argocd

# !!! NOTE: Always use separate fucking generators for configMaps + HELM
# !!!       REMEMBER THIS FACT!

generators:
  - generators/configmap-argocd-cm.yaml

resources:
  - patches/traefik-middleware.yaml
  - patches/config-map-tls.yaml
  - patches/cm-cmp-plugin.yaml
