config:
  secret:
    argocdServerAdminPassword: BLEEGASTAN123

server:
  insecure: true
  extraArgs:
    - --basehref            ## This is very important
    - /argocd               ## for non-standard "/someURL" configs
  ingress:
    enabled: true
    path: /argocd           ## This is very important for non-standard "/someURL" configs
    hostname: kubernetes.docker.internal
    tls: false
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: web
      traefik.ingress.kubernetes.io/router.middlewares: argocd-argocd-prefix@kubernetescrd
  extraVolumes:             ## Mocking TLS configmap mount for ApplicationSets requirements
    - name: tls-certs
      configMap:
        name: argocd-tls-certs-cm
  extraVolumeMounts:
    - mountPath: /app/config/tls
      name: tls-certs


repoServer:
  # ConfigManagement Plugin sidecar teengz!
  extraVolumes:
    - name: plugin-cmp-kustomize-helm
      configMap:
        name: plugin-cmp-kustomize-helm
    - emptyDir: {}
      name: var-files
    - emptyDir: {}
      name: plugins
    - emptyDir: {}
      name: tmp
    - emptyDir: {}
      name: helm-working-dir
  initContainers:
    - name: copyutil
      image: quay.io/argoproj/argocd:v2.2.1
      command:
        - cp
        - -n
        - /usr/local/bin/argocd
        - /var/run/argocd/argocd-cmp-server
      volumeMounts:
      - mountPath: /var/run/argocd
        name: var-files
  sidecars:
    - name: cmp
      command: [/var/run/argocd/argocd-cmp-server] # Entrypoint should be Argo CD lightweight CMP server i.e. argocd-cmp-server
      image: busybox # This can be off-the-shelf or custom built image
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
      volumeMounts:
        - mountPath: /var/run/argocd
          name: var-files
        - mountPath: /home/argocd/cmp-server/plugins
          name: plugins
        - mountPath: /home/argocd/cmp-server/config/plugin.yaml # Plugin config file can either be volume mapped or baked into image
          subPath: plugin.yaml
          name: plugin-cmp-kustomize-helm
        - mountPath: /tmp
          name: tmp

redis:
  auth:
    enabled: false
  master:
    persistence:
      enabled: false

  replica:
    replicaCount: 1
    persistence:
      enabled: false
