apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# namespace: argocd

helmGlobals:
  chartHome: synced/

helmCharts:
- name: helm-chart
  namespace: sealed-secrets
  releaseName: sealed-secrets
  includeCRDs: true
  valuesFile: values.yaml

# generators:
#   - generators/configmap-argocd-cm.yaml

# resources:
#   - patches/traefik-middleware.yaml
#   #- patches/cmp-plugin.yaml
