# I'll be a real file someday
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmGlobals:
  chartHome: synced/

helmCharts:
-
  name: helm-chart
  releaseName: argocd-applicationset
  namespace: argocd
  includeCRDs: true
  valuesFile: values.yaml

patches:
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/command/-
        value: '--log-level=warn'
    target:
      kind: Deployment
